# Generated by Django 6.0.2 on 2026-03-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
